import { Event } from '../types';

export const mockEvents: Event[] = [
  {
    id: 'e1',
    title: 'Hackathon 2026 Kickoff',
    description: 'Join us for the 24-hour coding marathon. Form teams, build cool projects, and win exciting prizes!',
    start_time: '2026-06-10T09:00:00Z',
    end_time: '2026-06-11T09:00:00Z',
    location: 'Main Auditorium',
    category: 'tech',
    source: 'official',
    status: 'published',
    is_free: true,
    price: null,
    poster_url: null,
    created_at: new Date().toISOString(),
    view_count: 142,
    star_count: 35,
    rsvp_going_count: 50,
    submitter_id: null
  },
  {
    id: 'e2',
    title: 'Inter-Hostel Music Night',
    description: 'A night of live sets as hostels battle it out across genres — acoustic, rock, indie and fusion. Open to all!',
    start_time: '2026-06-12T19:00:00Z',
    end_time: '2026-06-12T22:30:00Z',
    location: 'Open Air Theater',
    category: 'cultural',
    source: 'official',
    status: 'published',
    is_free: false,
    price: '₹100',
    poster_url: null,
    created_at: new Date().toISOString(),
    view_count: 300,
    star_count: 89,
    rsvp_going_count: 120,
    submitter_id: null
  },
  {
    id: 'e3',
    title: 'Sunday Morning Run 5K',
    description: 'Casual 5K run for beginners and intermediates. Meet at the main gate. Hydration provided!',
    start_time: '2026-06-14T06:00:00Z',
    end_time: '2026-06-14T07:30:00Z',
    location: 'Main Gate',
    category: 'sports',
    source: 'community',
    status: 'community',
    is_free: true,
    price: null,
    poster_url: null,
    created_at: new Date().toISOString(),
    view_count: 45,
    star_count: 12,
    rsvp_going_count: 8,
    submitter_id: 'user_123'
  },
  {
    id: 'e4',
    title: 'Resume Review Session',
    description: 'Seniors will be reviewing resumes for the upcoming placement season. Bring physical copies.',
    start_time: '2026-06-15T18:00:00Z',
    end_time: '2026-06-15T20:00:00Z',
    location: 'Library Room 4A',
    category: 'academic',
    source: 'community',
    status: 'community',
    is_free: true,
    price: null,
    poster_url: null,
    created_at: new Date().toISOString(),
    view_count: 88,
    star_count: 45,
    rsvp_going_count: 30,
    submitter_id: 'user_456'
  },
  {
    id: 'e5',
    title: 'Game Night: Board Games & Pizza',
    description: 'Relax after midterms with Catan, Monopoly, and free pizza. First come first serve.',
    start_time: '2026-06-16T19:30:00Z',
    end_time: '2026-06-16T22:00:00Z',
    location: 'Student Lounge',
    category: 'social',
    source: 'official',
    status: 'published',
    is_free: true,
    price: null,
    poster_url: null,
    created_at: new Date().toISOString(),
    view_count: 210,
    star_count: 70,
    rsvp_going_count: 90,
    submitter_id: null
  }
];
